name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    permissions:
      checks: write
      contents: read
      id-token: write
      packages: write
      pull-requests: write
      repository-projects: write

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main

    - run: nix build --impure --accept-flake-config .#kafka
    - run: nix build --impure --accept-flake-config .#spark
    - run: nix build --impure --accept-flake-config .#scalapuff
